### ISSUE TITLE
mkdoc changes

### ISSUE THREAD

**Issue by ianyu93** [piisa/piisa#10]
Now that we have [PIISA](http://piisa.org/) as our first version, this issue is created to track minor changes that we'd like to make for the current version. This is mainly for things like use of languages, typos, formatting, etc.

We aim to create the PR for this issue by Jan 15. 

If possible, please match the site with Markdown files [here](https://github.com/piisa/piisa/tree/main/docs) and link to the source files.

**Comment by ianyu93** [comment]
Bullet points [here](https://github.com/piisa/piisa/blob/main/docs/index.md#rationale) are not formatted properly for display. 

See how it's displayed on the site.
<img width="860" alt="image" src="https://user-images.githubusercontent.com/63731742/210810730-2271e626-4f3b-4c4d-bd22-fc7b3fa89d0c.png">

**Comment by paulovn** [comment]
The specification document https://piisa.org/specs/ is mostly fine, but the file format examples at the end have lost the newlines so the formatting is scrambled

**Comment by paulovn** [comment]
The usage document https://piisa.org/usage/ has also lost bullet points, but interestingly *not all of them*

I tend to think that the way to keep bullet lists is to have a blank line _before_ the bullet list, so that the bullets are not merged with the previous paragraph. Must have something to do with the supported markdown version

**Comment by hessiej** [comment]
The only thing I see right now --- and I haven't looked at the entire piece, 

PIISA = "Personally" NOT "Personal" 
should read: Personal**ly** Identifiable Information

**Comment by ianyu93** [comment]
> The only thing I see right now --- and I haven't looked at the entire piece,
> 
> PIISA = "Personally" NOT "Personal" should read: Personal**ly** Identifiable Information

We may need to check out throughout different repos later on for this then.

**Comment by ddeepika** [comment]
@ianyu93 A few minor edits: 
* Libraries (typo - currently is Libaries)
* Can we feature the link to the blog more prominently on this site? Maybe have it right under the PIISA section?
* Indicate that our framework is open source and interoperable in the definition?
* Include a use cases section that can be both current examples (where it is being applied such as BigCode) and forward looking (can be used here potentially...) ?
